---
title: "MUSA 5080 Portfolio"
---

# Welcome to My Portfolio

This portfolio documents my learning journey in Public Policy Analytics (MUSA 5080).

## About This Course
Advanced spatial analysis and data science for urban planning and public policy.

## Portfolio Structure
- **Weekly Notes:** My learning reflections and key concepts
- **Labs:** Completed assignments and analyses
- **Final Project:** Capstone modeling challenge

## About Me
I am Shaurya Chauhan, a Masters in City Planning candidate at University of Pennsylvania and an Architect with 5 years of professional experience in the urban development space.
I am currently pursuing my interest in the urban innovation space. Spatial Data Anayltics is thus a skill I'm polishing now- ideally at the intersection between tech and urban development- as well as its policy and ethical implications. This portfolio is my collected work in these forays. 
I am always open to collaborative projects in this space. Please find my contact details below.

## Contact
- Email: sholly31@upenn.edu
- GitHub: @Shaurya-Chauhan
