{
  "hash": "5b23d9882754b2d716261953091efa92",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Shaurya Chauhan\"\ndate: 10 february 2026\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\ngetwd()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"C:/Users/bhanu/OneDrive/Desktop/Post Grad Work/Sem 2/PPA/PortfolioPPA/labs/lab_2\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load spatial data\nhospitals <- st_read(here(\"data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\bhanu\\OneDrive\\Desktop\\Post Grad Work\\Sem 2\\PPA\\PortfolioPPA\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- tracts(state = \"PA\", cb = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\npa_counties <- st_read(here(\"data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\bhanu\\OneDrive\\Desktop\\Post Grad Work\\Sem 2\\PPA\\PortfolioPPA\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\npa_counties\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\nFirst 10 features:\n   OBJECTID MSLINK COUNTY_NAM COUNTY_NUM FIPS_COUNT COUNTY_ARE COUNTY_PER\n1       336     46 MONTGOMERY         46        091       <NA>       <NA>\n2       337      8   BRADFORD         08        015       <NA>       <NA>\n3       338      9      BUCKS         09        017       <NA>       <NA>\n4       339     58      TIOGA         58        117       <NA>       <NA>\n5       340     59      UNION         59        119       <NA>       <NA>\n6       341     60    VENANGO         60        121       <NA>       <NA>\n7       342     62 WASHINGTON         62        125       <NA>       <NA>\n8       343     63      WAYNE         63        127       <NA>       <NA>\n9       344     42     MCKEAN         42        083       <NA>       <NA>\n10      345     43     MERCER         43        085       <NA>       <NA>\n   NUMERIC_LA COUNTY_N_1 AREA_SQ_MI SOUND SPREAD_SHE IMAGE_NAME NOTE_FILE VIDEO\n1           5         46   487.4271  <NA>       <NA>   poll.bmp      <NA>  <NA>\n2           2          8  1161.3379  <NA>       <NA>   poll.bmp      <NA>  <NA>\n3           5          9   622.0836  <NA>       <NA>   poll.bmp      <NA>  <NA>\n4           2         58  1137.2480  <NA>       <NA>   poll.bmp      <NA>  <NA>\n5           2         59   319.1893  <NA>       <NA>   poll.bmp      <NA>  <NA>\n6           3         60   683.3676  <NA>       <NA>   poll.bmp      <NA>  <NA>\n7           1         62   862.1077  <NA>       <NA>   poll.bmp      <NA>  <NA>\n8           2         63   750.8286  <NA>       <NA>   poll.bmp      <NA>  <NA>\n9           1         42   985.2700  <NA>       <NA>   poll.bmp      <NA>  <NA>\n10          3         43   682.3598  <NA>       <NA>   poll.bmp      <NA>  <NA>\n   DISTRICT_N PA_CTY_COD MAINT_CTY_ DISTRICT_O                       geometry\n1          06         46          4        6-4 MULTIPOLYGON (((-8398884 48...\n2          03         08          9        3-9 MULTIPOLYGON (((-8558633 51...\n3          06         09          1        6-1 MULTIPOLYGON (((-8367360 49...\n4          03         59          7        3-7 MULTIPOLYGON (((-8558633 51...\n5          03         60          8        3-8 MULTIPOLYGON (((-8562865 49...\n6          01         61          5        1-5 MULTIPOLYGON (((-8870781 50...\n7          12         63          4       12-4 MULTIPOLYGON (((-8935296 48...\n8          04         64          6        4-6 MULTIPOLYGON (((-8368003 50...\n9          02         42          5        2-5 MULTIPOLYGON (((-8705967 51...\n10         01         43          4        1-4 MULTIPOLYGON (((-8956031 50...\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3445 features and 13 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -80.51989 ymin: 39.7198 xmax: -74.68952 ymax: 42.26986\nGeodetic CRS:  NAD83\nFirst 10 features:\n   STATEFP COUNTYFP TRACTCE              GEOIDFQ       GEOID   NAME\n1       42      001  031101 1400000US42001031101 42001031101 311.01\n2       42      013  100400 1400000US42013100400 42013100400   1004\n3       42      013  100500 1400000US42013100500 42013100500   1005\n4       42      013  100800 1400000US42013100800 42013100800   1008\n5       42      013  101900 1400000US42013101900 42013101900   1019\n6       42      011  011200 1400000US42011011200 42011011200    112\n7       42      011  000200 1400000US42011000200 42011000200      2\n8       42      011  011500 1400000US42011011500 42011011500    115\n9       42      011  000600 1400000US42011000600 42011000600      6\n10      42      011  001900 1400000US42011001900 42011001900     19\n              NAMELSAD STUSPS   NAMELSADCO   STATE_NAME LSAD   ALAND AWATER\n1  Census Tract 311.01     PA Adams County Pennsylvania   CT 3043185      0\n2    Census Tract 1004     PA Blair County Pennsylvania   CT  993724      0\n3    Census Tract 1005     PA Blair County Pennsylvania   CT 1130204      0\n4    Census Tract 1008     PA Blair County Pennsylvania   CT  996553      0\n5    Census Tract 1019     PA Blair County Pennsylvania   CT  573726      0\n6     Census Tract 112     PA Berks County Pennsylvania   CT 1539365   9308\n7       Census Tract 2     PA Berks County Pennsylvania   CT 1949529 159015\n8     Census Tract 115     PA Berks County Pennsylvania   CT 1978380  12469\n9       Census Tract 6     PA Berks County Pennsylvania   CT 1460473      0\n10     Census Tract 19     PA Berks County Pennsylvania   CT  182420      0\n                         geometry\n1  MULTIPOLYGON (((-77.03108 3...\n2  MULTIPOLYGON (((-78.42478 4...\n3  MULTIPOLYGON (((-78.41661 4...\n4  MULTIPOLYGON (((-78.41067 4...\n5  MULTIPOLYGON (((-78.40836 4...\n6  MULTIPOLYGON (((-75.95433 4...\n7  MULTIPOLYGON (((-75.96071 4...\n8  MULTIPOLYGON (((-75.99913 4...\n9  MULTIPOLYGON (((-75.91528 4...\n10 MULTIPOLYGON (((-75.91819 4...\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\nFirst 10 features:\n                  CHIEF_EXEC              CHIEF_EX_1\n1              Peter J Adamo               President\n2           Autumn DeShields Chief Executive Officer\n3               Shawn Parekh Chief Executive Officer\n4                DIANE HRITZ Chief Executive Officer\n5             Tim Harclerode Chief Executive Officer\n6  Richard McLaughlin MD MBA Chief Executive Officer\n7             Laura Murnyack             Interim CEO\n8                  Adam Beck Chief Executive Officer\n9                Pamela Keen Chief Executive Officer\n10              Mark Papalia           President/CEO\n                                 FACILITY_U LONGITUDE       COUNTY\n1              https://www.phhealthcare.org -79.91131   Washington\n2                 https://www.malvernbh.com -75.17005 Philadelphia\n3            https://roxboroughmemorial.com -75.20963 Philadelphia\n4                https://www.ashospital.net -80.27907   Washington\n5                 https://www.conemaugh.org -79.02513     Somerset\n6                   https://towerhealth.org -75.61213   Montgomery\n7         https://bucktailmedicalcenter.org -77.73649      Clinton\n8  https://www.selectspecialtyhospitals.com -76.88013      Dauphin\n9          https://www.childrenshomepgh.org -79.93736    Allegheny\n10    https://www.kanecommunityhospital.com -78.81705       McKean\n                                                  FACILITY_N\n1                                  Penn Highlands Mon Valley\n2                                  MALVERN BEHAVIORAL HEALTH\n3                               Roxborough Memorial Hospital\n4                                 ADVANCED SURGICAL HOSPITAL\n5                    DLP Conemaugh Meyersdale Medical Center\n6                                    Pottstown Hospital, LLC\n7                                    Bucktail medical Center\n8  SELECT SPECIALTY HOSPITAL CENTRAL PENNSYLVANIA HARRISBURG\n9                          The Children's Home of Pittsburgh\n10              University of Pittsburgh Medical Center Kane\n                           STREET   CITY_OR_BO LATITUDE   TELEPHONE_ ZIP_CODE\n1          1163 Country Club Road  Monongahela 40.18193 724-258-1000    15063\n2  1930 South Broad Street Unit 4 Philadelphia 39.92619 610-480-8919    19145\n3               5800 Ridge Avenue Philadelphia 40.02869 215-483-9900    19128\n4        100 TRICH DRIVE\\nSUITE 1   WASHINGTON 40.15655   7248840710    15301\n5              200 Hospital Drive   Meyersdale 39.80913 814-634-5911    15552\n6           1600 East High Street    Pottstown 40.24273   6103277000    19464\n7                1001 Pine Street       Renovo 41.32789 570-923-1000    17764\n8          111 South Front Street   Harrisburg 40.25841 717-724-6604    17110\n9                5324 Penn Avenue   Pittsburgh 40.46424 412-441-4884    15224\n10                4372 US Route 6         Kane 41.67188   8148378585    16735\n                     geometry\n1  POINT (-79.91131 40.18193)\n2   POINT (-75.17005 39.9262)\n3  POINT (-75.20963 40.02869)\n4  POINT (-80.27907 40.15655)\n5  POINT (-79.02513 39.80913)\n6  POINT (-75.61213 40.24273)\n7  POINT (-77.73649 41.32789)\n8  POINT (-76.88013 40.25842)\n9  POINT (-79.93736 40.46424)\n10 POINT (-78.81705 41.67188)\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- st_transform(pa_tracts, st_crs(pa_counties))\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n223 Hospitals.\n\n- How many census tracts?\n3445 Census Tracts.\n\n- What coordinate reference system is each dataset in?\nCounties and Hospitals are in WGS 84, Tracts are in NAD 83.\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\ntract_demographics <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2022,\n  survey = \"acs5\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\",\n    \n    male_65_66 = \"B01001_020\",\n    male_67_69 = \"B01001_021\",\n    male_70_74 = \"B01001_022\",\n    male_75_79 = \"B01001_023\",\n    male_80_84 = \"B01001_024\",\n    male_85_plus = \"B01001_025\",\n    \n    female_65_66 = \"B01001_044\",\n    female_67_69 = \"B01001_045\",\n    female_70_74 = \"B01001_046\",\n    female_75_79 = \"B01001_047\",\n    female_80_84 = \"B01001_048\",\n    female_85_plus = \"B01001_049\"\n  ),\n  output = \"wide\"\n)\n #65 plus population summing\ntract_demographics <- tract_demographics %>%\n  mutate(\n    pop_65_plus =\n      male_65_66E + male_67_69E + male_70_74E +\n      male_75_79E + male_80_84E + male_85_plusE +\n      female_65_66E + female_67_69E + female_70_74E +\n      female_75_79E + female_80_84E + female_85_plusE\n  )\n\n\n# Join to tract boundaries\npa_tracts_demographics <- pa_tracts %>%\n  left_join(\n    tract_demographics,\n    by = \"GEOID\"\n  )\n\nsum(is.na(pa_tracts_demographics$median_incomeE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(pa_tracts_demographics$median_incomeE, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n2022 \n\n- How many tracts have missing income data?\n62 tracts\n\n- What is the median income across all PA census tracts?\nIt is $70,188\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n# Calculate the percentage of elderly residents in each tract. This converts the elderly population count into a comparable rate\n\npa_tracts_demographics <- pa_tracts_demographics %>%\n  mutate(\n    pct_elderly = (pop_65_plus / total_popE) * 100\n  )\n\n# Define the income threshold\n# Using the median tract-level income across Pennsylvania as a relative benchmark for \"low income\"\nincome_threshold <- median(\n  pa_tracts_demographics$median_incomeE,\n  na.rm = TRUE\n)\n\n# Define the elderly population threshold\n# Tracts above the median percentage elderly are considered to have a significant elderly population\nelderly_threshold <- median(\n  pa_tracts_demographics$pct_elderly,\n  na.rm = TRUE\n)\n\n# Filter for vulnerable tracts\n# A tract is considered vulnerable if it meets BOTH conditions:- median income below the income threshold & percentage elderly above the elderly threshold\nvulnerable_tracts <- pa_tracts_demographics %>%\n  filter(\n    median_incomeE < income_threshold,\n    pct_elderly > elderly_threshold\n  )\n\n# Checking how many tracts meet the vulnerability criteria\nnrow(vulnerable_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 822\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate the percentage of all PA census tracts that are classified as vulnerable under this definition\nround(\n  nrow(vulnerable_tracts) / nrow(pa_tracts_demographics) * 100,\n  1\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.9\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\nI used the median household income across Pennsylvania census tracts as the threshold. This provides a relative, state-specific benchmark for identifying economically vulnerable neighborhoods without relying on arbitrary cutoffs.\n\n- What elderly population threshold did you choose and why?\nI used the median percentage of residents aged 65 and over across Pennsylvania census tracts. Using a percentage (rather than a count) allows comparison across tracts of different sizes and highlights areas with above-average healthcare needs.\n\n- How many tracts meet your vulnerability criteria?\n822 census tracts meet both vulnerability criteria (low income and high elderly population).\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\nApproximately 23.9% of Pennsylvania census tracts are classified as vulnerable under this definition.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\n# Project vulnerable tracts to a distance-preserving CRS\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, 3365)\n\n# Project hospitals to the same CRS\nhospitals_proj <- st_transform(hospitals, 3365)\n\n# Calculate distance from each tract centroid to nearest hospital\n\n# Calculate centroids of vulnerable census tracts\nvulnerable_centroids <- st_centroid(vulnerable_tracts_proj)\n\n# Calculate distance matrix between tract centroids and hospitals\ndistance_matrix <- st_distance(\n  vulnerable_centroids,\n  hospitals_proj\n)\n\n# For each tract, find distance to nearest hospital (in miles)\nvulnerable_centroids <- vulnerable_centroids %>%\n  mutate(\n    dist_to_nearest_hospital_miles =\n      as.numeric(apply(distance_matrix, 1, min)) / 5280\n  )\n\n\navg_distance <- mean(\n  vulnerable_centroids$dist_to_nearest_hospital_miles,\n  na.rm = TRUE\n)\navg_distance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.764526\n```\n\n\n:::\n\n```{.r .cell-code}\nmax_distance <- max(\n  vulnerable_centroids$dist_to_nearest_hospital_miles,\n  na.rm = TRUE\n)\nmax_distance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 29.11587\n```\n\n\n:::\n\n```{.r .cell-code}\nn_far_tracts <- sum(\n  vulnerable_centroids$dist_to_nearest_hospital_miles > 15,\n  na.rm = TRUE\n)\nn_far_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\nThe average distance from vulnerable census tracts to the nearest hospital is approximately 5.7 miles.\n\n- What is the maximum distance?\nThe maximum distance from a vulnerable census tract to the nearest hospital is approximately 29 miles, indicating extreme geographic isolation in some areas.\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n50\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\n# Create an underserved indicator\nvulnerable_centroids <- vulnerable_centroids %>%\n  mutate(\n    underserved = dist_to_nearest_hospital_miles > 15\n  )\n\n\nn_underserved <- sum(vulnerable_centroids$underserved, na.rm = TRUE)\nn_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n\n```{.r .cell-code}\npct_underserved <- round(\n  n_underserved / nrow(vulnerable_centroids) * 100,\n  1\n)\npct_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.1\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n50 tracts.\n\n- What percentage of vulnerable tracts are underserved?\n6.1% are underserved.\n\n- Does this surprise you? Why or why not?\nThis result is not surprising, as Pennsylvania’s large hospital density mgiht mask rural access gaps that disproportionately affect a small but important subset of vulnerable communities.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_counties_proj <- st_transform(pa_counties, 3365)\n\n# Spatial join tracts to counties\ntracts_with_county <- vulnerable_centroids %>%\n  st_join(pa_counties_proj %>% select(COUNTY_NAM))\n\n# Aggregating statistics by county\ncounty_summary <- tracts_with_county %>%\n  st_drop_geometry() %>%  # removing geometry for clean aggregation\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    # Number of vulnerable tracts\n    n_vulnerable_tracts = n(),\n    \n    # Number of underserved tracts\n    n_underserved_tracts = sum(underserved, na.rm = TRUE),\n    \n    # Percentage of vulnerable tracts underserved\n    pct_underserved = round(\n      n_underserved_tracts / n_vulnerable_tracts * 100,\n      1\n    ),\n    \n    # Average distance to nearest hospital\n    avg_distance_miles = round(\n      mean(dist_to_nearest_hospital_miles, na.rm = TRUE),\n      2\n    ),\n    \n    # Total vulnerable population\n    total_vulnerable_population = sum(pop_65_plus, na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\ncounty_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 68 × 6\n   COUNTY_NAM n_vulnerable_tracts n_underserved_tracts pct_underserved\n   <chr>                    <int>                <int>           <dbl>\n 1 CAMERON                      2                    2           100  \n 2 FOREST                       1                    1           100  \n 3 SULLIVAN                     3                    3           100  \n 4 PIKE                         6                    4            66.7\n 5 JUNIATA                      4                    2            50  \n 6 SNYDER                       4                    2            50  \n 7 CLEARFIELD                  16                    7            43.8\n 8 HUNTINGDON                   7                    2            28.6\n 9 POTTER                       7                    2            28.6\n10 BRADFORD                    11                    3            27.3\n# ℹ 58 more rows\n# ℹ 2 more variables: avg_distance_miles <dbl>,\n#   total_vulnerable_population <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_summary %>%\n  arrange(desc(n_underserved_tracts)) %>%\n  select(COUNTY_NAM, n_underserved_tracts) %>%\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  COUNTY_NAM n_underserved_tracts\n  <chr>                     <int>\n1 CLEARFIELD                    7\n2 PIKE                          4\n3 SULLIVAN                      3\n4 BRADFORD                      3\n5 CAMERON                       2\n```\n\n\n:::\n\n```{.r .cell-code}\n# For counties with most vulnerable people\ncounty_population_summary <- tracts_with_county %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    vulnerable_pop_far = sum(\n      ifelse(underserved, pop_65_plus, 0),\n      na.rm = TRUE\n    )\n  ) %>%\n  arrange(desc(vulnerable_pop_far))\n\nhead(county_population_summary, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  COUNTY_NAM vulnerable_pop_far\n  <chr>                   <dbl>\n1 CLEARFIELD               5856\n2 BRADFORD                 3385\n3 PIKE                     2127\n4 LANCASTER                1857\n5 SNYDER                   1839\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nCameron, Forest, SUllivan, Pike and Juniata counties have the highest % od underserved tracts.\n\n- Which counties have the most vulnerable people living far from hospitals?\nThe counties with the highest number of vulnerable residents living more than 15 miles from a hospital are Clearfield, Bradford, Pike, Lancaster and Snyder.\n\n- Are there any patterns in where underserved counties are located?\nThe counties with the highest percentage of underserved vulnerable tracts are primarily small, rural counties in northern and central Pennsylvania (e.g., Cameron, Forest, Sullivan). These counties have relatively few hospitals and large geographic areas, which increases travel distances. Meanwhile, counties with the highest number of vulnerable residents living far from hospitals (e.g., Clearfield, Bradford, Pike) tend to be geographically large rural counties with dispersed populations. This indicates that geographic isolation and low facility density are the main drivers of healthcare access inequities.\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating and formatting priority counties table\nlibrary(knitr)\n\npriority_table <- county_population_summary %>%\n  left_join(county_summary, by = \"COUNTY_NAM\") %>%\n  arrange(desc(vulnerable_pop_far)) %>%\n  slice_head(n = 10) %>%\n  select(\n    County = COUNTY_NAM,\n    `Vulnerable Residents >15 Miles` = vulnerable_pop_far,\n    `Vulnerable Tracts` = n_vulnerable_tracts,\n    `Underserved Tracts` = n_underserved_tracts,\n    `% Underserved` = pct_underserved,\n    `Avg Distance (Miles)` = avg_distance_miles\n  )\n\n# Formatting and displaying table\nkable(\n  priority_table,\n  caption = \"Top 10 Priority Counties for Healthcare Investment Based on Vulnerable Populations with Limited Hospital Access\",\n  format.args = list(big.mark = \",\"),\n  align = \"lrrrrr\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment Based on Vulnerable Populations with Limited Hospital Access\n\n|County     | Vulnerable Residents >15 Miles| Vulnerable Tracts| Underserved Tracts| % Underserved| Avg Distance (Miles)|\n|:----------|------------------------------:|-----------------:|------------------:|-------------:|--------------------:|\n|CLEARFIELD |                          5,856|                16|                  7|          43.8|                14.15|\n|BRADFORD   |                          3,385|                11|                  3|          27.3|                10.62|\n|PIKE       |                          2,127|                 6|                  4|          66.7|                17.47|\n|LANCASTER  |                          1,857|                10|                  2|          20.0|                 7.04|\n|SNYDER     |                          1,839|                 4|                  2|          50.0|                15.40|\n|HUNTINGDON |                          1,692|                 7|                  2|          28.6|                12.43|\n|CRAWFORD   |                          1,682|                16|                  2|          12.5|                 7.86|\n|TIOGA      |                          1,589|                10|                  2|          20.0|                10.67|\n|SULLIVAN   |                          1,306|                 3|                  3|         100.0|                21.52|\n|CAMERON    |                          1,269|                 2|                  2|         100.0|                19.07|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\nCounties were prioritized based on the total number of vulnerable residents living more than 15 miles from the nearest hospital. This metric captures both socioe-conomic vulnerability and geographic isolation, ensuring that investment targets areas with the greatest concentration of healthcare access inequities.\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\nlibrary(ggplot2)\n\n# Joining summary statistics back to county geometry\ncounties_for_map <- pa_counties_proj %>%\n  left_join(county_summary, by = \"COUNTY_NAM\")\n\n# Creating choropleth map\nggplot() +\n  # County polygons filled by % underserved\n  geom_sf(\n    data = counties_for_map,\n    aes(fill = pct_underserved),\n    color = \"white\",\n    size = 0.2\n  ) +\n  \n  # Hospital locations\n  geom_sf(\n    data = hospitals_proj,\n    color = \"black\",\n    size = 1,\n    alpha = 0.7\n  ) +\n  \n  # Color scale\n  scale_fill_viridis_c(\n    option = \"magma\",\n    name = \"% Vulnerable\\nTracts Underserved\",\n    labels = function(x) paste0(x, \"%\"),\n    na.value = \"grey90\"\n  ) +\n  \n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Percentage of Vulnerable Census Tracts Located More Than 15 Miles from a Hospital\",\n    caption = \"Source: ACS 2018–2022, Pennsylvania Hospital Data | Analysis by Shaurya Chauhan\"\n  ) +\n  \n  theme_void() +\n  \n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\n# Separating underserved and served tracts for clarity\nunderserved_tracts <- vulnerable_centroids %>%\n  filter(underserved == TRUE)\n\nserved_tracts <- vulnerable_centroids %>%\n  filter(underserved == FALSE)\n\nggplot() +\n  \n  # County boundaries for context\n  geom_sf(\n    data = pa_counties_proj,\n    fill = NA,\n    color = \"grey70\",\n    size = 0.3\n  ) +\n  \n  # Served vulnerable tracts (light color)\n  geom_sf(\n    data = served_tracts,\n    color = \"lightblue\",\n    size = 1,\n    alpha = 0.6\n  ) +\n  \n  # Underserved vulnerable tracts (highlighted)\n  geom_sf(\n    data = underserved_tracts,\n    color = \"red\",\n    size = 1.5,\n    alpha = 0.9\n  ) +\n  \n  # Hospital locations\n  geom_sf(\n    data = hospitals_proj,\n    color = \"black\",\n    size = 1,\n    alpha = 0.8\n  ) +\n  \n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Red = Vulnerable tracts >15 miles from a hospital | Light blue = Vulnerable tracts within 15 miles\",\n    caption = \"Source: ACS 2018–2022, Pennsylvania Hospital Data | Analysis by Shaurya Chauhan\"\n  ) +\n  \n  theme_void() +\n  \n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nggplot(vulnerable_centroids, \n       aes(x = dist_to_nearest_hospital_miles)) +\n  \n  geom_histogram(\n    bins = 30,\n    fill = \"steelblue\",\n    color = \"white\",\n    alpha = 0.8\n  ) +\n  \n  geom_vline(\n    xintercept = 15,\n    color = \"red\",\n    linetype = \"dashed\",\n    size = 1\n  ) +\n  \n  labs(\n    title = \"Distribution of Distance to Nearest Hospital\\nAmong Vulnerable Census Tracts\",\n    x = \"Distance to Nearest Hospital (Miles)\",\n    y = \"Number of Vulnerable Census Tracts\",\n    caption = \"Red dashed line indicates 15-mile underserved threshold\"\n  ) +\n  \n  theme_minimal() +\n  \n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    axis.title = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nlibrary(sf)\nlibrary(here)\n\n# Load parks shapefile\nphilly_parks <- st_read(here(\"labs/lab_2/PPR_Properties/PPR_Properties.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Properties' from data source \n  `C:\\Users\\bhanu\\OneDrive\\Desktop\\Post Grad Work\\Sem 2\\PPA\\PortfolioPPA\\labs\\lab_2\\PPR_Properties\\PPR_Properties.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 504 features and 25 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8380525 ymin: 4847239 xmax: -8344359 ymax: 4885123\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\n# Basic inspection of parks dataset\nnrow(philly_parks)                 # Number of park features\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 504\n```\n\n\n:::\n\n```{.r .cell-code}\nst_geometry_type(philly_parks)[1]  # Geometry type\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] MULTIPOLYGON\n18 Levels: GEOMETRY POINT LINESTRING POLYGON MULTIPOINT ... TRIANGLE\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(philly_parks)               # CRS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(philly_parks)                # Column names\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"public_nam\" \"parent_nam\" \"nested\"     \"official_n\" \"label\"     \n [6] \"alias\"      \"dpp_asset_\" \"address_91\" \"zip_code\"   \"address_br\"\n[11] \"alias_addr\" \"acreage\"    \"property_c\" \"ppr_use\"    \"ppr_prog_d\"\n[16] \"ppr_ops_di\" \"council_di\" \"police_dis\" \"city_scale\" \"local_scal\"\n[21] \"program_si\" \"comments\"   \"objectid\"   \"Shape__Are\" \"Shape__Len\"\n[26] \"geometry\"  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Transform parks to PA State Plane South\nphilly_parks_proj <- st_transform(philly_parks, 3365)\nst_crs(philly_parks_proj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3365 \n  wkt:\nPROJCRS[\"NAD83(HARN) / Pennsylvania South (ftUS)\",\n    BASEGEOGCRS[\"NAD83(HARN)\",\n        DATUM[\"NAD83 (High Accuracy Reference Network)\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4152]],\n    CONVERSION[\"SPCS83 Pennsylvania South zone (US survey foot)\",\n        METHOD[\"Lambert Conic Conformal (2SP)\",\n            ID[\"EPSG\",9802]],\n        PARAMETER[\"Latitude of false origin\",39.3333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-77.75,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",40.9666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",39.9333333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1968500,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",0,\n            LENGTHUNIT[\"US survey foot\",0.304800609601219],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"US survey foot\",0.304800609601219]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"United States (USA) - Pennsylvania - counties of Adams; Allegheny; Armstrong; Beaver; Bedford; Berks; Blair; Bucks; Butler; Cambria; Chester; Cumberland; Dauphin; Delaware; Fayette; Franklin; Fulton; Greene; Huntingdon; Indiana; Juniata; Lancaster; Lawrence; Lebanon; Lehigh; Mifflin; Montgomery; Northampton; Perry; Philadelphia; Schuylkill; Snyder; Somerset; Washington; Westmoreland; York.\"],\n        BBOX[39.71,-80.53,41.18,-74.72]],\n    ID[\"EPSG\",3365]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nI selected the Philadelphia Parks & Recreation (PPR) Properties dataset- which contains the spatial boundaries of park properties and land managed by Philadelphia Parks & Recreation. I chose this dataset because access to publicly managed green space is closely linked to public health, environmental justice and neighborhood quality of life. Evaluating spatial access to park land in relation to vulnerable populations allows for a meaningful equity-focused analysis relevant to urban planning and public investment decisions.\n\n- What is the data source and date?\nThe dataset was obtained from OpenDataPhilly, provided by Philadelphia Parks & Recreation (PPR).\nSource: Philadelphia Parks & Recreation via OpenDataPhilly (2018 dataset).\n\n- How many features does it contain?\nThe dataset contains 504 multipolygon features, where each feature represents a park property or managed land boundary within Philadelphia.\n\n- What CRS is it in? Did you need to transform it?\nThe dataset is originally projected in WGS 84 / Pseudo-Mercator (EPSG:3857), which uses meters as units and is commonly used for web mapping applications. Because accurate buffering and area calculations require a locally appropriate projected coordinate system, I transformed the dataset to NAD83 / Pennsylvania South State Plane (EPSG:3365), which uses feet as linear units and is better suited for distance-based spatial analysis within Pennsylvania.\n\n---\n\n2. **Pose a research question**\n\nAre census tracts in Philadelphia with below-median income and above-median elderly population disproportionately lacking walkable access (within 0.25 miles) to publicly managed park land- using tract centroids as a proxy for residential location?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n\n\n# Extract Philadelphia Census Tracts (FIPS 42101)\nphilly_tracts <- pa_tracts %>%\n  filter(substr(GEOID, 1, 5) == \"42101\")\n\n\n# Transform BOTH layers to PA State Plane South (EPSG 3365, feet)\nphilly_tracts_proj <- st_transform(philly_tracts, 3365)\nphilly_parks_proj  <- st_transform(philly_parks, 3365)\n\n\n# Join Demographic Data\nphilly_tracts_proj <- philly_tracts_proj %>%\n  left_join(\n    pa_tracts_demographics %>%\n      st_drop_geometry() %>%\n      select(GEOID, median_incomeE, pop_65_plus, total_popE),\n    by = \"GEOID\"\n  )\n\n\n# Calculate elderly percentage\nphilly_tracts_proj <- philly_tracts_proj %>%\n  mutate(\n    pct_elderly = (pop_65_plus / total_popE) * 100\n  )\n\n\n# Define Vulnerability (Philly thresholds)\nphilly_income_threshold <- median(\n  philly_tracts_proj$median_incomeE,\n  na.rm = TRUE\n)\n\nphilly_elderly_threshold <- median(\n  philly_tracts_proj$pct_elderly,\n  na.rm = TRUE\n)\n\nphilly_tracts_proj <- philly_tracts_proj %>%\n  mutate(\n    vulnerable = median_incomeE < philly_income_threshold &\n                 pct_elderly > philly_elderly_threshold\n  )\n\n\n# 0.25 miles = 1320 feet buffer\npark_buffers <- philly_parks_proj %>%\n  st_buffer(dist = 1320)\n\n# Merge overlapping buffers\npark_coverage_area <- st_union(park_buffers)\n\n\n\n# Use TRACT CENTROIDS for Access Test\ntract_centroids <- st_centroid(philly_tracts_proj)\n\n# Determine whether centroid falls inside park buffer\ntract_centroids <- tract_centroids %>%\n  mutate(\n    has_park_access =\n      st_intersects(geometry, park_coverage_area, sparse = FALSE)[,1]\n  )\n\n\n# Compare Park Access by Vulnerability\npark_equity_summary <- tract_centroids %>%\n  st_drop_geometry() %>%\n  group_by(vulnerable) %>%\n  summarize(\n    total_tracts = n(),\n    tracts_with_access = sum(has_park_access),\n    tracts_without_access = sum(!has_park_access),\n    pct_without_access =\n      (tracts_without_access / total_tracts) * 100\n  )\n\n\n\n# Joining park access back to tract polygons\nphilly_tracts_proj <- philly_tracts_proj %>%\n  left_join(\n    tract_centroids %>%\n      st_drop_geometry() %>%\n      select(GEOID, has_park_access),\n    by = \"GEOID\"\n  )\n\n\n\n# Creating simple equity category for mapping\nphilly_tracts_proj <- philly_tracts_proj %>%\n  mutate(\n    equity_flag = case_when(\n      vulnerable & !has_park_access ~ \"Vulnerable – No Access\",\n      vulnerable & has_park_access ~ \"Vulnerable – Has Access\",\n      TRUE ~ \"Other Tracts\"\n    )\n  )\n\n\n\nggplot() +\n  \n  # Park polygons (light background)\n  geom_sf(\n    data = philly_parks_proj,\n    fill = \"lightgreen\",\n    color = NA,\n    alpha = 0.3\n  ) +\n  \n  # Census tracts colored by equity category\n  geom_sf(\n    data = philly_tracts_proj,\n    aes(fill = equity_flag),\n    color = \"white\",\n    size = 0.1\n  ) +\n  \n  scale_fill_manual(\n    values = c(\n      \"Vulnerable – No Access\" = \"red\",\n      \"Vulnerable – Has Access\" = \"orange\",\n      \"Other Tracts\" = \"grey80\"\n    ),\n    name = \"Tract Type\"\n  ) +\n  \n  labs(\n    title = \"Walkable Park Access in Philadelphia\",\n    subtitle = \"Access defined as centroid within 0.25 miles of park land\",\n    caption = \"Source: ACS 2018–2022 and PPR Properties\"\n  ) +\n  \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\nThe results indicate a measurable equity gap in walkable park access across Philadelphia. Approximately 29% of socioeconomically vulnerable census tracts lack access to park land within a 0.25-mile walking distance, compared to 21% of non-vulnerable tracts. This 8-percentage-point difference suggests that neighborhoods with lower incomes and higher elderly populations face systematically reduced proximity to public green space. While Philadelphia overall has relatively dense park coverage, access at a shorter walking threshold reveals localized disparities. These findings suggest that targeted investments in small neighborhood parks, green corridors, or pedestrian infrastructure may be warranted in vulnerable areas.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you received after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}