{
  "hash": "3b761a5e5fd1909dd832b25b33c8b338",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Shaurya Chauhan\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n## Overview\n\nThis analysis builds a spatial predictive model of burglary incidents in Chicago using neighborhood-level indicators of urban disorder. \n\nThe primary predictor used in this study is 311 garbage cart complaints, which serve as a proxy for neighborhood maintenance and disorder. Prior research suggests that visible signs of neglect may be associated with higher crime risk by reducing informal social control.\n\nThe objective is to evaluate whether incorporating spatial features derived from garbage complaints improves the prediction of burglary incidents compared to simple spatial smoothing methods such as kernel density estimation (KDE).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(here)\nlibrary(viridis)\nlibrary(terra)\nlibrary(spdep)\nlibrary(FNN)\nlibrary(MASS)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(classInt)\n\nlibrary(spatstat.geom)\nlibrary(spatstat.explore)\n\noptions(scipen = 999)\nset.seed(5080)\n\ntheme_crime <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\ntheme_set(theme_crime())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: C:/Users/bhanu/OneDrive/Desktop/Post Grad Work/Sem 2/PPA/PortfolioPPA/labs/lab_4 \n```\n\n\n:::\n:::\n\n\n\n## Exercise 1.1: Load Chicago Spatial Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n:::\n\n\nThe analysis begins by loading key spatial boundary datasets for Chicago, \nincluding police districts, police beats, and the city boundary. These \ngeographies provide the spatial framework for the analysis.\n\nPolice districts are particularly important because they are used for spatial \ncross-validation, allowing the model to be evaluated on unseen geographic areas.\n\nAll datasets are transformed to a common coordinate reference system \n(ESRI:102271) to ensure consistency in spatial operations.\n\n\n## Exercise 1.2: Load Burglary Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nburglaries <- st_read(here(\"data\", \"burglaries.shp\")) %>% \n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `C:\\Users\\bhanu\\OneDrive\\Desktop\\Post Grad Work\\Sem 2\\PPA\\PortfolioPPA\\data\\burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(burglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7,482\nColumns: 23\n$ ID       <int> 10801247, 10801593, 10801602, 10801904, 10801956, 10802305, 1…\n$ Cs_Nmbr  <chr> \"JA100159\", \"JA100586\", \"JA100376\", \"JA100943\", \"JA101022\", \"…\n$ Date     <date> 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-02, 2017-01-01, …\n$ Block    <chr> \"048XX N KEDZIE AVE\", \"054XX W CHICAGO AVE\", \"057XX S MOZART …\n$ IUCR     <chr> \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610…\n$ Prmry_T  <chr> \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"…\n$ Dscrptn  <chr> \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIB…\n$ Lctn_Ds  <chr> \"RESTAURANT\", \"SMALL RETAIL STORE\", \"RESIDENCE-GARAGE\", \"RESI…\n$ Arrest   <chr> \"true\", \"false\", \"false\", \"true\", \"false\", \"false\", \"false\", …\n$ Domestc  <chr> \"false\", \"false\", \"false\", \"false\", \"false\", \"false\", \"false\"…\n$ Beat     <int> 1713, 1524, 824, 722, 724, 1723, 732, 935, 1432, 334, 2533, 1…\n$ Distrct  <int> 17, 15, 8, 7, 7, 17, 7, 9, 14, 3, 25, 12, 16, 25, 3, 4, 12, 1…\n$ Ward     <int> 33, 37, 16, 6, 17, 39, 17, 3, 1, 7, 37, 1, 38, 31, 5, 7, 1, 4…\n$ Cmmnt_A  <int> 14, 25, 63, 69, 67, 16, 68, 61, 21, 43, 25, 24, 15, 20, 43, 4…\n$ FBI_Cod  <chr> \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"…\n$ X_Crdnt  <int> 1154172, 1139598, 1158356, 1176576, 1168818, 1150614, 1172237…\n$ Y_Crdnt  <int> 1931913, 1904799, 1866496, 1859716, 1860109, 1928503, 1856217…\n$ Year     <int> 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2…\n$ Updtd_O  <date> 2017-02-14, 2017-02-14, 2017-02-14, 2018-02-10, 2017-02-14, …\n$ Latitud  <dbl> 41.96900, 41.89488, 41.78940, 41.77041, 41.77166, 41.95971, 4…\n$ Longitd  <dbl> -87.70849, -87.76275, -87.69490, -87.62830, -87.65672, -87.72…\n$ Locatin  <chr> \"(41.968999706, -87.708494241)\", \"(41.894875219, -87.76274673…\n$ geometry <POINT [m]> POINT (351792.8 588847.4), POINT (347350.6 580583), POI…\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ Loaded burglary data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded burglary data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of burglaries: 7482 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n:::\n\n\nThe dataset contains burglary incidents across Chicago for 2017. The data is \nstored as a spatial point dataset and transformed into the ESRI:102271 \ncoordinate system to enable accurate distance-based analysis.\n\n\n## Exercise 1.3: Visualize Crime Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  )\n\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(option = \"plasma\", direction = -1) +\n  labs(\n    title = \"Burglary Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/visualize-burglaries-1.png){width=960}\n:::\n:::\n\nBurglary incidents are spatially clustered rather than randomly distributed \nacross Chicago- especially around the south-eastern and central Chicago areas. The density map reveals concentrated hotspots of crime, \nindicating that these neighborhoods experience significantly higher levels \nof burglary.\n\nThis clustering suggests that spatial features and neighborhood conditions \nplay a critical role in explaining crime patterns, making spatial modeling \nessential for prediction.\n\n\n## Exercise 2.1: Create Spatial Analysis Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 1000,\n  square = TRUE\n) %>%\n  st_as_sf() %>%\n  st_intersection(chicagoBoundary)\n\nfishnet$grid_id <- 1:nrow(fishnet)\n\nnrow(fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 656\n```\n\n\n:::\n:::\n\n\nA regular grid (fishnet) is created to aggregate crime data into spatial units. \nEach grid cell represents a 1000-foot square area, allowing crime counts and \nother features to be measured consistently across space.\n\nThis approach converts point-level data into area-based observations, which \nare required for regression modeling.\n\n\n## Exercise 2.2: Aggregate Crime Counts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet$crime_count <- lengths(\n  st_intersects(fishnet, burglaries)\n)\n\nsummary(fishnet$crime_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    2.00    9.00   11.37   18.00   62.00 \n```\n\n\n:::\n:::\n\n\nCrime counts are calculated for each grid cell by counting the number of \nburglary incidents that fall within each spatial unit. This creates the \ndependent variable for the regression model.\n\nThe distribution of crime counts is typically skewed, with many cells \nhaving low counts and a smaller number of cells experiencing high crime.\n\n\n## Exercise 3.1: Load Garbage Cart Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngarbage_raw <- read_csv(here(\"data\", \"Chicago_GarbageCarts.csv\"))\n\n# Remove rows with missing coordinates\ngarbage_clean <- garbage_raw %>%\n  drop_na(Longitude, Latitude)\n\n# Convert to sf\ngarbage <- garbage_clean %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n\ncat(\"✓ Garbage data loaded\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Garbage data loaded\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Original rows:\", nrow(garbage_raw), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Original rows: 52851 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - After cleaning:\", nrow(garbage), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - After cleaning: 52837 \n```\n\n\n:::\n:::\n\n\nGarbage cart locations are incorporated as an additional spatial feature. \nThe dataset is converted into a spatial format and projected into the same \ncoordinate system as the rest of the analysis.\n\nThis variable serves as a proxy for neighborhood conditions and municipal \nservice patterns, which may be associated with crime levels.\n\n\n## Exercise 3.2: Aggregate Garbage Carts to Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet$garbage_count <- lengths(\n  st_intersects(fishnet, garbage)\n)\n\nsummary(fishnet$garbage_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00   17.00   73.00   80.44  129.25  351.00 \n```\n\n\n:::\n:::\n\n\nGarbage cart counts are calculated for each grid cell to capture the spatial \ndistribution of waste management infrastructure.\n\nAreas with higher concentrations of garbage carts may reflect higher population \ndensity or different neighborhood characteristics, which could influence crime patterns.\n\n\n## Exercise 3.3: Create Spatial Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get coordinates of grid centroids\ncoords <- st_coordinates(st_centroid(fishnet))\n\n# Use knearneigh (spdep-compatible)\nknn_obj <- knearneigh(coords, k = 4)\n\n# Convert to neighbors list\nneighbors <- knn2nb(knn_obj)\n\n# Create spatial weights\nweights <- nb2listw(neighbors, style = \"W\")\n\n# Spatial lag of crime\nfishnet$crime_lag <- lag.listw(weights, fishnet$crime_count)\n\nsummary(fishnet$crime_lag)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    4.25   10.12   11.64   17.25   42.50 \n```\n\n\n:::\n:::\n\n\nSpatial features are created to capture spatial dependence in crime patterns. \nNearest neighbor distances measure how close each grid cell is to others, while \nspatial lag captures the average crime levels in neighboring cells.\n\nThese features allow the model to account for spatial autocorrelation, where \ncrime in one area is influenced by crime in nearby areas.\n\n\n## Exercise 3.4: Attach Police Districts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet <- st_join(fishnet, policeDistricts)\n\ntable(fishnet$District)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1 10 11 12 14 15 16 17 18 19  2 20 22 24 25  3 31  4  5  6  7  8  9 \n25 32 26 40 27 15 69 37 26 36 29 22 59 23 40 28 16 93 51 31 25 82 51 \n```\n\n\n:::\n:::\n\n\nPolice district identifiers are attached to each grid cell. These are later \nused for spatial cross-validation, ensuring that model evaluation is performed \nacross distinct geographic areas rather than random splits.\n\n\n## Exercise 4.1: Negative Binomial Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_model <- glm.nb(\n  crime_count ~ garbage_count + crime_lag,\n  data = fishnet\n)\n\nsummary(nb_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = crime_count ~ garbage_count + crime_lag, data = fishnet, \n    init.theta = 2.463219887, link = log)\n\nCoefficients:\n              Estimate Std. Error z value            Pr(>|z|)    \n(Intercept)   0.822556   0.048028   17.13 <0.0000000000000002 ***\ngarbage_count 0.004972   0.000420   11.84 <0.0000000000000002 ***\ncrime_lag     0.075581   0.003285   23.01 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(2.4632) family taken to be 1)\n\n    Null deviance: 2274.8  on 882  degrees of freedom\nResidual deviance: 1107.1  on 880  degrees of freedom\nAIC: 5532.2\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  2.463 \n          Std. Err.:  0.175 \n\n 2 x log-likelihood:  -5524.156 \n```\n\n\n:::\n:::\n\n\n\nA Negative Binomial regression model is used to predict burglary counts. This \nmodel is appropriate because crime data are count-based and typically exhibit \noverdispersion, where the variance exceeds the mean.\n\nThe model includes garbage cart density and spatial lag of crime. Garbage carts \nserve as a proxy for neighborhood conditions and service patterns, while the \nspatial lag captures the influence of nearby areas. Together, these variables \nallow the model to account for both environmental and spatial drivers of crime.\n\nThe Negative Binomial regression results indicate that both garbage cart density \nand spatial lag are statistically significant predictors of burglary counts.\n\nThe coefficient for **garbage_count (0.00497, p < 0.001)** is positive and highly \nsignificant, suggesting that areas with more garbage carts tend to experience \nslightly higher burglary counts. While the magnitude is modest, this variable \nlikely captures underlying neighborhood characteristics such as density or \nactivity levels rather than a direct causal relationship.\n\nThe coefficient for **crime_lag (0.0756, p < 0.001)** is substantially larger and \nalso highly significant. This indicates strong spatial dependence, meaning that \ncrime in a given location is heavily influenced by crime levels in neighboring \nareas. This is consistent with well-established patterns of crime clustering in \nurban environments.\n\n\n\n## Exercise 4.2: Model Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet$predicted <- predict(nb_model, type = \"response\")\n\nsummary(fishnet$predicted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  2.276   4.055   7.812  13.996  17.257 300.121 \n```\n\n\n:::\n:::\n\n\n\n\n## Exercise 4.3: Predicted Crime Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = predicted), color = NA) +\n  scale_fill_viridis_c(option = \"plasma\") +\n  labs(\n    title = \"Predicted Burglary Counts\",\n    fill = \"Predicted\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/prediction-map-1.png){width=672}\n:::\n:::\n\n\n\nThe predicted burglary map reveals clear spatial clustering of crime across \nChicago. High predicted values are concentrated in specific hotspot areas, \nparticularly in central and southern regions, indicating that the model is \nsuccessfully identifying areas with elevated crime risk.\n\nThe model produces a smoother surface compared to raw crime counts, which is \nexpected in regression-based predictions. This smoothing reflects the model’s \nability to generalize underlying spatial patterns rather than overfitting to \nextreme observations.\n\nThe alignment between predicted hotspots and known high-crime areas suggests \nthat the model captures key spatial dynamics effectively. In particular, the \nstrong influence of spatial lag contributes to the formation of these clustered \nprediction patterns.\n\n\n\n## Exercise 4.3: Spatial Cross Validation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistricts <- unique(fishnet$District)\n\ncv_results <- map_dfr(districts, function(d) {\n  \n  train <- fishnet %>% filter(District != d)\n  test  <- fishnet %>% filter(District == d)\n  \n  model <- glm.nb(\n    crime_count ~ garbage_count + crime_lag,\n    data = train\n  )\n  \n  test$pred <- predict(model, newdata = test, type = \"response\")\n  \n  tibble(\n    district = d,\n    rmse = sqrt(mean((test$crime_count - test$pred)^2, na.rm = TRUE))\n  )\n})\n\ncv_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 23 × 2\n   district  rmse\n   <chr>    <dbl>\n 1 5         4.90\n 2 4         8.97\n 3 22        4.70\n 4 31        2.30\n 5 6        14.9 \n 6 8        21.8 \n 7 7        17.9 \n 8 3        21.1 \n 9 2         8.82\n10 9         6.91\n# ℹ 13 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(cv_results$rmse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.10908\n```\n\n\n:::\n:::\n\n\nSpatial cross-validation using a leave-one-district-out (LOGO) approach produced \nan average RMSE of approximately **13.11 burglaries per grid cell**.\n\nThe RMSE values vary substantially across districts, ranging from as low as \napproximately **2.3** to over **21**, indicating uneven predictive performance \nacross the city. This variation suggests that the model performs well in some \ndistricts but struggles in others, particularly in areas with more complex or \nvolatile crime patterns.\n\nThe relatively higher RMSE values compared to what would be expected under random \ncross-validation highlight the challenge of spatial generalization. When the model \nis tested on entirely unseen geographic areas, prediction errors increase, \ndemonstrating that crime patterns are highly localized.\n\nOverall, these results emphasize that while the model captures general spatial \ntrends, its ability to transfer across different neighborhoods is limited, \nreflecting underlying spatial heterogeneity in urban crime dynamics.\n\n\n\n\n## Conclusions\n\nThis analysis demonstrates that burglary patterns in Chicago are strongly shaped \nby spatial dynamics. The results show that crime is not randomly distributed but \nhighly clustered, with nearby areas exerting significant influence on each other.\n\nThe Negative Binomial model confirms that **spatial lag is the most important \npredictor**, highlighting the importance of spatial dependence in crime modeling. \nGarbage cart density is also statistically significant, suggesting that it \ncaptures underlying neighborhood characteristics such as density or activity \nlevels.\n\nThe model achieves moderate predictive performance, with an average RMSE of \napproximately **13 burglaries per grid cell** under spatial cross-validation. \nHowever, the variation in RMSE across districts indicates that prediction accuracy \nis uneven and context-dependent.\n\nThese findings underscore two key insights:  \n1. **Incorporating spatial features is essential for accurate crime prediction**  \n2. **Models struggle to generalize across different neighborhoods due to spatial heterogeneity**\n\nFrom a policy perspective, this suggests that city interventions should be \n**place-specific rather than one-size-fits-all**, and predictive models should be \nused alongside local knowledge when allocating resources.\n\nOverall, the analysis demonstrates the value of combining spatial data, \nneighborhood indicators, and appropriate modeling techniques to better understand \nand predict urban crime patterns.\n\n\n\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}